export const BRANDS = [
  "Hot Wheels",
  "Matchbox",
  "Majorette",
  "Tomica",
  "Maisto",
  "Bburago",
  "Welly",
  "Jada Toys",
  "Johnny Lightning",
  "Mini GT",
  "Tarmac Works",
  "INNO64",
  "POP RACE",
  "GreenLight",
  "Auto World",
  "M2 Machines",
  "Era Car",
  "FuelMe",
  "GCD",
  "Hobby Japan",
  "Ignition Model",
  "AutoArt",
  "Kyosho",
  "Minichamps",
  "Spark",
  "Norev",
  "Schuco",
  "Solido",
  "IXO",
  "Almost Real",
  "GT Spirit",
  "Otto Mobile",
  "CMC",
  "BBR",
  "MR Collection",
  "Looksmart",
  "Amalgam",
  "Diecast Masters",
  "Tonkin Replicas",
  "First Gear",
  "Norscot",
  "Speccast",
  "Hobby Master",
  "Dragon Models",
  "Forces of Valor",
  "JC Wings",
  "GeminiJets",
  "Kinsmart",
  "Motormax",
  "Road Signature",
  "Cararama",
  "Siku",
  "Dinky Toys",
  "Corgi",
  "Tekno",
  "Tamiya",
  "TSM Model",
  "TopSpeed",
  "Paragon Models",
  "Oxford Diecast",
  "Premium ClassiXXs",
  "Vitesse",
]
export const COLORS = [
  "Antifreeze",
  "Apple Green",
  "Aqua",
  "Beige",
  "Berry",
  "Black",
  "Blue",
  "Brick Red",
  "Brown",
  "Brushed Metal",
  "Burgundy",
  "Candy Red",
  "Charcoal",
  "Chocolate Brown",
  "Chrome",
  "Clear",
  "Copper",
  "Crimson",
  "Dark Aqua",
  "Dark Brown",
  "Dark Gray",
  "Deep Purple",
  "Emerald Green",
  "Gloss Black",
  "Gloss White",
  "Gold",
  "Gray",
  "Green",
  "Honey Gold",
  "Hot Pink",
  "Ice Blue",
  "Lavender",
  "Lime Green",
  "Magenta",
  "Matte Army Green",
  "Matte Black",
  "Matte Gray",
  "Metallic Black",
  "Metallic Blue",
  "Metallic Copper",
  "Metallic Gold",
  "Metallic Green",
  "Metallic Orange",
  "Metallic Purple",
  "Metallic Red",
  "Metallic Silver",
  "Metallic Teal",
  "Navy Blue",
  "Olive Gold",
  "Olive Green",
  "Orange",
  "Pearl Blue",
  "Pearl Green",
  "Pearl Red",
  "Pearl White",
  "Pink",
  "Plum",
  "Purple",
  "Red",
  "Root Beer Brown",
  "Rose",
  "Roxy",
  "Salmon Pink",
  "Silver",
  "Sky Blue",
  "Smoke Tint",
  "Spectraflame Aqua",
  "Spectraflame Blue",
  "Spectraflame Green",
  "Spectraflame Orange",
  "Spectraflame Purple",
  "Spectraflame Red",
  "Tan",
  "Translucent Blue",
  "Translucent Red",
  "Violet",
  "Watermelon",
  "White",
  "Windex Blue",
  "Yellow",
  "Zamac",
]
