export const FREE_ITEMS_LIMIT = 50
export const FREE_FAVORITES_LIMIT = 3
export const BRANDS = [
  "Hot Wheels",
  "Matchbox",
  "Majorette",
  "Tomica",
  "Maisto",
  "Bburago",
  "Welly",
  "Jada Toys",
  "Johnny Lightning",
  "Mini GT",
  "Tarmac Works",
  "INNO64",
  "POP RACE",
  "GreenLight",
  "Auto World",
  "M2 Machines",
  "Era Car",
  "FuelMe",
  "GCD",
  "Hobby Japan",
  "Ignition Model",
  "AutoArt",
  "Kyosho",
  "Minichamps",
  "Spark",
  "Norev",
  "Schuco",
  "Solido",
  "IXO",
  "Almost Real",
  "GT Spirit",
  "Otto Mobile",
  "CMC",
  "BBR",
  "MR Collection",
  "Looksmart",
  "Amalgam",
  "Diecast Masters",
  "Tonkin Replicas",
  "First Gear",
  "Norscot",
  "Speccast",
  "Hobby Master",
  "Dragon Models",
  "Forces of Valor",
  "JC Wings",
  "GeminiJets",
  "Kinsmart",
  "Motormax",
  "Road Signature",
  "Cararama",
  "Siku",
  "Dinky Toys",
  "Corgi",
  "Tekno",
  "Tamiya",
  "TSM Model",
  "TopSpeed",
  "Paragon Models",
  "Oxford Diecast",
  "Premium ClassiXXs",
  "Vitesse",
]
